### ISSUE TITLE
After today's upgrade, the Mijia plugin will not enable the entire homebridge

### ISSUE THREAD

**Issue by Guoer-xz** [Maxmudjon/homebridge-mijia#4]
After today's upgrade, the Mijia plugin will not enable the entire homebridge

————————————————————————————————————————————
/usr/local/lib/node_modules/homebridge-mijia/lib/MiJiaPlatform.js:180
	if (err) throw err
	         ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/homebridge-mijia/158d0000f……

**Comment by Guoer-xz** [comment]
It is very strange that the use of Mijia plug-in with sudo homebridge can start the service, there is no Mijia plug-in can also use homebridge to start the service directly, I do not know what caused the problem of permissions

**Comment by Maxmudjon** [comment]
I upgraded to version 1.2.78. Try to update

**Comment by Guoer-xz** [comment]
After the update, the homebridge service cannot be started even with sudo

————————————————————————————————————————————
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::57383
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:509:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:10)
logout

**Comment by Guoer-xz** [comment]
Restore and delete the Mijia plug-in all functions, only a switch with the same device 4 bit code using sudo can also appear in the case of wifi86 two keys before operation, the switch does not have any practical effect, the three operation button is still unable to work, then after a period of time there was three the recognition button disappeared two, smoke detectors and gas at this stage can not be identified, now basically will encounter these problems, thank you for your efforts to update and improve the stability, look forward to the future
